export const DASHBOARD_COPY = {
  PAGE_TITLE: 'Your bots',
  CREATE_BOT: 'Create bot',
  CREATE_FIRST_BOT: 'Create your first chatbot',
  EMPTY_STATE_DESCRIPTION:
    'Upload documents, test answers, and embed a widget on your site.',
  MODAL_CREATE_TITLE: 'Create bot',
  MODAL_EDIT_TITLE: 'Edit bot',
  BOT_NAME_LABEL: 'Bot name',
  BOT_NAME_PLACEHOLDER: 'Support Assistant',
  AVATAR_LABEL: 'Avatar URL (optional)',
  AVATAR_PLACEHOLDER: 'https://example.com/avatar.png',
  SUBMIT_CREATE: 'Create',
  SUBMIT_EDIT: 'Save changes',
  CANCEL: 'Cancel',
  VIEW_BOT: 'View bot',
  KNOWLEDGE_BASE: 'Knowledge base',
  EDIT_BOT: 'Edit bot',
  DOCUMENTS_SUFFIX: 'documents',
  LAST_UPDATED_PREFIX: 'Updated',
  STATUS_READY: 'Active',
  STATUS_PROCESSING: 'Processing',
  STATUS_DRAFT: 'Draft',
  CREATE_CARD_LABEL: 'Add another bot',
  SETTINGS: 'Settings',
  LOG_OUT: 'Log out',
  USER_MENU_LABEL: 'Account menu',
  INVALID_NAME: 'Enter a bot name to continue.',
} as const
